### GET request to example server
GET {{host}}/api/article/FEATURES/2?pageSize=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjpbIlNVUEVSX0FETUlOIl0sIm5hbWUiOiLsobDsnbjtmIEiLCJpZCI6MSwidHlwZSI6IkFDQ0VTUyIsImlhdCI6MTcyNzMwMjg1NywiZXhwIjoxNzI3Mzg5MjU3fQ.rZj1n87ScYy2UYwZq65rspdh1_iTaR7eRfCkvJKS8G8

###
