### GET Article Line Page
GET {{host}}/api/admin/article/FEATURES/2?pageSize=10&containInvisible=true
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IuyhsOyduO2YgSIsInJvbGUiOlsiU1VQRVJfQURNSU4iXSwidHlwZSI6IkFDQ0VTUyIsImlhdCI6MTcyODQ2MzM4NSwiZXhwIjoxODE0ODYzMzg1fQ.3lNPx8Ww4eUWEFcQfVWfpDACYGAxWWi0EFcyY8RrkdY


### GET Article Detail
GET {{host}}/api/admin/article/113
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IuyhsOyduO2YgSIsInJvbGUiOlsiU1VQRVJfQURNSU4iXSwidHlwZSI6IkFDQ0VTUyIsImlhdCI6MTcyODQ2MzM4NSwiZXhwIjoxODE0ODYzMzg1fQ.3lNPx8Ww4eUWEFcQfVWfpDACYGAxWWi0EFcyY8RrkdY


### GET Recent Article
GET {{host}}/api/admin/article/recent?count=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IuyhsOyduO2YgSIsInJvbGUiOlsiU1VQRVJfQURNSU4iXSwidHlwZSI6IkFDQ0VTUyIsImlhdCI6MTcyODQ2MzM4NSwiZXhwIjoxODE0ODYzMzg1fQ.3lNPx8Ww4eUWEFcQfVWfpDACYGAxWWi0EFcyY8RrkdY


### Upload article(invisible:true로 안보이게 설정됨)
POST {{host}}/api/admin/article
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IuyhsOyduO2YgSIsInJvbGUiOlsiU1VQRVJfQURNSU4iXSwidHlwZSI6IkFDQ0VTUyIsImlhdCI6MTcyODQ2MzM4NSwiZXhwIjoxODE0ODYzMzg1fQ.3lNPx8Ww4eUWEFcQfVWfpDACYGAxWWi0EFcyY8RrkdY

{
  "title": "테스트 기사 입니다.",
  "pictureUrl": "https://snuquill-public-s3.s3.ap-northeast-2.amazonaws.com/photo/article/3104c9df-1ac9-4b6b-b41c-9f68a7850bad.png",
  "category": "FEATURES",
  "contents": "테스트입니다.",
  "authorId": 15,
  "invisible": true
}

### Modify article
POST {{host}}/api/admin/article/126
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IuyhsOyduO2YgSIsInJvbGUiOlsiU1VQRVJfQURNSU4iXSwidHlwZSI6IkFDQ0VTUyIsImlhdCI6MTcyODQ2MzM4NSwiZXhwIjoxODE0ODYzMzg1fQ.3lNPx8Ww4eUWEFcQfVWfpDACYGAxWWi0EFcyY8RrkdY

{
  "title": "테스트 기사입니다.2",
  "pictureUrl": "https://snuquill-public-s3.s3.ap-northeast-2.amazonaws.com/photo/article/3104c9df-1ac9-4b6b-b41c-9f68a7850bad.png",
  "category": "FEATURES",
  "contents": "테스트입니다.2",
  "authorId": 15,
  "invisible": false
}


### Change article visibility
POST {{host}}/api/admin/article/126/visibility
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IuyhsOyduO2YgSIsInJvbGUiOlsiU1VQRVJfQURNSU4iXSwidHlwZSI6IkFDQ0VTUyIsImlhdCI6MTcyODQ2MzM4NSwiZXhwIjoxODE0ODYzMzg1fQ.3lNPx8Ww4eUWEFcQfVWfpDACYGAxWWi0EFcyY8RrkdY

{
  "invisible": false
}
