### 로그인
POST {{host}}/api/admin/auth/login
Content-Type: application/json

{
  "email": "alzpqm@naver.com",
  "password": "98dlsgur"
}


### Token 재발급
POST {{host}}/api/admin/auth/renew
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ0eXBlIjoiQUNDRVNTIiwiaWQiOjEsIm5hbWUiOiLsobDsnbjtmIEiLCJyb2xlIjpbIlNVUEVSX0FETUlOIl0sImlhdCI6MTcyNjY1MTQxMywiZXhwIjoxNzI2NzM3ODEzfQ.Ac_vb_Dkrqkq3Sb-Y_jTYW5Y_hBJc7MM9wly1mXGTOo
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJ0eXBlIjoiUkVGUkVTSCIsImlkIjoxLCJpYXQiOjE3MjY2NTE0MTMsImV4cCI6MTcyNzg2MTAxM30.DdkWqeyG2Lbznp97yGr-yDWXdxu3el9DGbHcImI5ob4


### 암호화 된 비밀번호 확인
GET  {{host}}/api/admin/auth/encode-password?pw=abcde1234
Content-Type: application/json
