### Post EditorPick
POST {{host}}/api/admin/editorPick/feature
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ0eXBlIjoiQUNDRVNTIiwiaWQiOjEsIm5hbWUiOiLsobDsnbjtmIEiLCJyb2xlIjpbIlNVUEVSX0FETUlOIl0sImlhdCI6MTcyNjY1MTQyOCwiZXhwIjoxNzI2NzM3ODI4fQ.v8ybmzxoFRt0sNO9hbpiglWf0TvReyUd4eC9Poz_GgI

{
  "id": 93
}


### Get EditorPick
GET {{host}}/api/admin/editorPick
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IuyhsOyduO2YgSIsInJvbGUiOlsiU1VQRVJfQURNSU4iXSwidHlwZSI6IkFDQ0VTUyIsImlhdCI6MTcyNzYxNzQ5MiwiZXhwIjoxNzI3NzAzODkyfQ.WEPykhx-kNTF4SNd6dub7Ek8tSPoWYrDPEOZZWtod-s
