### GET request to example server
POST {{host}}/api/admin/editorPick/features
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ0eXBlIjoiQUNDRVNTIiwiaWQiOjEsIm5hbWUiOiLsobDsnbjtmIEiLCJpYXQiOjE3MjM5ODcxMzUsImV4cCI6MTgxMDM4NzEzNX0.soLIl8vA7GOEQo7qjvo5Qclbv1-21YVfGxYqyYKtdUQ

{
  "id": 93
}
