### GET Magazine
GET {{host}}/api/admin/photoJournal/lastVolume
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IuyhsOyduO2YgSIsInJvbGUiOlsiU1VQRVJfQURNSU4iXSwidHlwZSI6IkFDQ0VTUyIsImlhdCI6MTcyNzYxNzQ5MiwiZXhwIjoxNzI3NzAzODkyfQ.WEPykhx-kNTF4SNd6dub7Ek8tSPoWYrDPEOZZWtod-s
